### ISSUE TITLE
Provide sample results

### ISSUE THREAD

**Issue by brauliobo** [jruby/bench9000#2]
It is very hard to reproduce all tests provided. Could you please provide a sample result?

**Comment by chrisseaton** [comment]
Sample results now here https://github.com/jruby/bench9000/tree/master/example.

When you say it's hard to reproduce I hope you mean it's time consuming, rather than you're having difficulty running the tool or getting the same results as we have?

Total time for running all benchmarks in all configurations is about 10 days, so I know it's not quick, but you should be able to run a smaller set in a lot less time.

**Comment by brauliobo** [comment]
Sorry, could not find the sample results. Very nice!

Yeah, I meant time consuming, mainly because there is a lot of dependencies.

So maybe the only thing that needs to be done is to link this example result on the README.

Anyway, congratulations for the incredible work on truffle performance! Really amazing. Hope to use it in production soon.
