### ISSUE TITLE
Performance of jRuby

### ISSUE THREAD

**Issue by kusumachalasani** [jruby/bench9000#8]
I'm doing some performance runs with jRuby v9.0.4 + bench 9000.  I run the benchmark using options.config file as
binary "c1", "jruby-9.0.4.0/bin/jruby", "-J-Xmx2G -Xcompile.invokedynamic=true"

My result consistently show that jRuby is taking around 8 times more time than Ruby-MRI, whereas in the bench9000 report (http://jruby.org/bench9000/), 
I see that you claim jRuby (with or without invokedynamic) performs  much better than cRuby - by around 9% (noindy), around 26% (indy). Attached the snapshots of the graphs for classic-binary-trees from the bench9000 report.
![warmup-classic-binary-trees](https://cloud.githubusercontent.com/assets/17760990/13665469/ab24f9e0-e6d2-11e5-9c9a-426e482b17e0.jpg)
![speedup-classic-binary-trees](https://cloud.githubusercontent.com/assets/17760990/13665470/ab2cde30-e6d2-11e5-8077-cae48906cc42.jpg)

I also tried on different architectures (IA32 / AMD64), but still I see same behaviour. I did my investigations more using classic-binary-trees. I see this discrepancy both with the Hotspot JVM and IBM J9 JVM. Were there any tuning parameters I should apply ?

Ruby MRI (ruby-2.2.2) takes around 3 seconds to complete.
Below are the scores (in sec) of bench9000 with jRuby v9.0.4 on LinuxAMD64 

IBM Java 8.0              Oracle 8u71-b15
noinvokedynamic (-Xcompile.invokedynamic=false)         22.94 		21.57
invokedynamic(-Xcompile.invokedynamic=true)               24.11 		25.56

Machine Details:
CPU Type: 	Intel 'E5-2670 Sandybridge' AMD64 (64-bit)
Compatible with: 	x86 (32-bit) 
CPUs: 	16 physical, 32 logical (multithreading: HT)

**Comment by headius** [comment]
I think you are looking at the "int" (as in interpreter) results rather than the "indy" (as in invokedynamic) results. As far as I can tell from your graphs, JRuby+indy is clearly faster than MRI or JRuby without indy.

This performance will also be improving rapidly over the next several months, starting with big perf fixes and improvements in the upcoming 9.1 release.

I don't see a problem here, so I'll close this.

**Comment by chrisseaton** [comment]
> I see that you claim jRuby

I should also add the that the JRuby team aren't claiming anything with bench9000 (unless they want to do so). These are my benchmarks written originally as part of my PhD. They are in the JRuby team's GitHub org, and they automatically appear on the JRuby website because of that.

I'm not entirely sure what you are saying, since you post JRuby scores, but note those that you observe for MRI. Are you comparing scores that you see locally against scores that you see in the bench9000 example report? You can't compare scores between machines I'm afraid.

Please feel free to ask for more help by opening an issue in the bench9000 repo. We can help you use the tool and interpret the results there, and if we still see an issue we can open an issue for it here with more concrete details.
